spring:
  profiles:
    include: oauth
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hyphen_user
    username: root
    hikari:
#      password: Qwe123!@#
      password: rnwkgus
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: ture
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

application:
  security:
    jwt:
      secretKey: 25432A462D4A614E645267556A586E3272357538782F413F4428472B4B625065
      expiration: 3600000 # 1 hour
      refreshExpiration: 1209600000 # 2 week

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

AdminMail:
  name: Hyphen
  id: g88080997@gmail.com
  password: mvkiamndnqiwedih

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
#  paths-to-match:
#    - /**
  model-and-view-allowed: true

webClient:
  servers:
    imageServer:
      path: http://101.101.217.155:8083